### PR TITLE
lt_abridged2single function

### PR DESCRIPTION
**Pull request by sarahertog**
Hi Tim,
Please see draft lt_abridged2single function to graduate abridged life table to single year of age using pclm() function of ungroup package. I've tried to retain all functionality of lt_single_mx.
Thanks!

### CODE REVIEW

**Comment by timriffe** [comment]
Thanks, good timing! I think I might just use this internally in some places

**Comment by timriffe** [comment]
Hi @sarahertog you'll want to check out my changes to `lt_abridged2single()`. I started just changing details, and adding an example. In my example I saw that the life expectancy at birth estimate was off by a few years, where I would have expected a difference in the second decimal place only. On investigation, I saw that `M`, as returned by `pclm()` was lower than the implied input rates `ndx/nLx`. I recalled having seen this behavior in our `pclm()` use in COVerAGE-DB. There we always follow `pclm()` with `rescaleAgeGroups()`, because we're always dealing with counts. `ndx` and `nLx` are essentially counts, and can be dealt with in similar fashion. So, the new strategy inside this function is 1) use PCLM on `nLx` 2) rescale resulting single age `Lx` 3) PCLM `ndx` using rescaled single-age `Lx` as offset, producing a first rate estimate, `M1` 4) get implied single-age `dx` by multiplying into rescaled single-age `Lx` 5) rescale resulting inferred `dx` 6) take ration of rescaled `dx` to rescaled `Lx` as the input rates to `lt_single_mx(). Resulting life expectancies at birth now differ only in the second decimal. That's an acceptable amount of error, so this function can be deployed I think.

In the future, the user should be able to choose between PCLM vs TOPALS, where TOPALS hasn't yet made it into `DemoTools`

**Comment by sarahertog** [comment]
Thanks, Tim. Indeed that is a problematic e0 difference!  I tested on the set of CD and UN model life tables already extended to 130+ and the e0 differences between abridged and single were all at the second decimal place.  I will study your code to better understand how rescale works.

**Comment by timriffe** [comment]
Great, I just opened an issue #171 regarding an aesthetic aspect of the
output, so this one is still prime for tinkering.

I'll pose a question about the scaling artifact to @mpascariu, the
`ungroup` maintainer.

**Comment by sarahertog** [comment]
It seems that pclm() is extremely sensitive to what's going on at the old-age tail and that it also doesn't like ndx or nLx between 0 and 1.  I tried first extending your example mortality pattern to age 130 and then ungrouping the integer ndx and nLx values.  The resulting e0 is 35.03 for the abridged and 35.01 for the single.  This explains why I didn't see large errors in testing on the the CD and UN mlts. 1) they were already extended to 130 and 2) ndx and nLx are integers in that dataset.

See based on your example: 

Age <- c(0,1,seq(5,85,5))
Mx <- c(.23669,.04672,.00982,.00511,.00697,.01036,.01169,
        .01332,.01528,.01757,.02092,.02517,.03225,.04241,.06056,
        .08574,.11840,.16226,.23745)

LTabr  <- lt_abridged(nMx = Mx,
                         Age = Age,
                         axmethod = "un",
                         Sex = "m",
                         mod = TRUE,
                         OAnew = 130)

M <- pclm(x = LTabr$Age[2:27],
          y = round(LTabr$ndx[2:27]),
          nlast = 5,
          offset = round(LTabr$nLx[2:27]))

LT1 <- lt_single_mx(nMx = c(LTabr$nMx[1], fitted(M)),
                        Sex = "m",
                        axmethod = "un",
                        a0rule = "ak",
                        OAG = FALSE)

LTabr$ex[1]
LT1$ex[1]

plot(LTabr$Age + (LTabr$AgeInt/2), log(LTabr$nMx))
lines(LT1$Age + (LT1$AgeInt/2), log(LT1$nMx))

**Comment by timriffe** [comment]
Will check it out, thanks. `ndx` and `nLx` don't strictly need to come from
lifetables. They could also be deaths and exposures. By extension, if using
lifetable arguments, we could overcome the small counts issue by inflating
the lifetable radix. We could indeed just declare the lifetable radix to be
1e6 or more (no need for it to scale to an actual population size for this
task). Then maybe it'll work better. In general, it's best to extrapolate
using `MortalityLaws()` via `lt_abridged()` in advance. We just make that a
default first step, that would reduce the risk of erratic upper tails. Then
cut down output to the requested `OAnew`. Sounds like a plan to me.

**Comment by timriffe** [comment]
new version pushed to master. Seems to have pretty good properties now. Insides are ugly though.

**Pull request merged**
