### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by tbernardesfaria**
Hi Tim,

Just committing some changes I made. They are not finalized.

### CODE REVIEW

**Comment by timriffe** [comment]
Hi, just checking- doe this PR include a committed `.Rdata` file? Those are things we want to `.gitignore` unless it's package data, but I don't think it is.

**Comment by tbernardesfaria** [comment]
It went wrong Tim. When I was updating the file it asked to commit or delete gitignore. I try to delete it, but of course, it went wrong...

**Comment by timriffe** [comment]
You can delete the file locally. In your git tab in Rstudio you'll see it turn red. Then you can commit the deletion and push. When you push it automatically adds to this PR. Are tests otherwise passing in this update?

**Comment by tbernardesfaria** [comment]
Hi Tim, I not sure, but I think I deleted the \code{gitignore} file. Also, I'm having trouble with cat function

**Pull request merged**
