### PR TITLE
RC estimating function

### PR DESCRIPTION
**Pull request by MJAlexander**
Start of the function that calls stan to estimate RC migration model

### CODE REVIEW

**Comment by timriffe** [comment]
Thanks! Appveyor gives a warning and note, both seem easy on the surface.
Somewhere in your PR or your fork you’ll see the appveyor fail in red. If
you click that you’ll get the log, quite long. Scroll down to where the R
checks actually start and you’ll see lots of notes in undeclared variables
being used. Not having looked at the code yet I assume this is from tidy
eval. Can you look for a sufficiently elegant solution and push that to
your fork? The warnings come from dependencies, easier to track down and
take care of. If you use something from another package use importFrom  in
the roxygen.

**Comment by MJAlexander** [comment]
Thanks @timriffe i think this is fixed now?

**Comment by timriffe** [comment]
I changed some `backtick` things to double quotes, and it doesn't throw errors, possibly because the estimation function isn't run in an example? Or maybe it's innocuous. Doing so removed many of the notes, however use of tidy eval is causing many notes, maybe this page can give some guidance re that: https://tidyr.tidyverse.org/articles/in-packages.html

**Comment by timriffe** [comment]
OK, got it under control. Needed to add some `@importFrom` in the header, and do things like change `variable` to `!!sym("variable")`, now passing with no notes. The innards have a different not-pretty look about them, very much not the original intent of those who designed the tidyverse, but this is what it's become... there are surely other hacks to make these things behave politely in packages, but this is the first solution I came to. Of course, `mig_estimate_rc()` still needs to be retested, and a running example would be great.

Some things I still don't understand: why `@import Rcpp` ? why not `@importFrom rstan extract` and `@importFrom rstan stan` ? Where does `.return_rc_stan_model()` come from? Just a few things I've noticed

**Comment by MJAlexander** [comment]
Thanks, I fixed a few errors that got introduced with the !!sym() stuff ( and the regex stuff didn't work when you took out the backticks, but all fixed now), got rid of the `gather()`, also removed Rcpp and added `@importFrom rstan extract` (not sure why I did that, I think error checking initially led me down that path). 

Re: `.return_rc_stan_model()`, it's here: https://github.com/timriffe/DemoTools/blob/master/R/return_rc_stan_model.R I made it hidden because I thought the DemoTools package user wouldn't really be needing/wanting it. 

Will add an example to the docs and do another PR.

**Comment by timriffe** [comment]
awesome thank you! I'll be working on DemoTools some tomorrow and will
check it out.

**Pull request merged**
